version: "3.9"
services:
  mysql:
    env_file: [.env_file]
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql/
  psql:
    env_file: [.env_file]
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data/
  redis:
    env_file: [.env_file]
    image: redis:latest
    restart: unless-stopped
    command: --requirepass pass
    ports:
      - 6379:6379
  mongo:
    env_file: [.env_file]
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
  ydb:
    env_file: [.env_file]
    image: cr.yandex/yc/yandex-docker-local-ydb:latest
    restart: unless-stopped
    ports:
      - 8765:8765
      # - 2135:2135
      - 2136:2136
    hostname: localhost
  dashboard:
    env_file: [.env_file]
    build:
      context: .
      dockerfile: ./dockerfile_stats
    image: superset_df_dashboard
    ports:
      - "8088:8088"
  clickhouse:
    env_file: [.env_file]
    image: yandex/clickhouse-server:latest
    restart: unless-stopped
    ports:
      - '8123:8123'
    volumes:
      - ch-data:/var/lib/clickhouse/
volumes:
  mysql-data: &volume-spec
    name: "mysql-data"
  ch-data:
    <<: *volume-spec
    name: "ch-data"
  pg-data:
    <<: *volume-spec
    name: "pg-data"