name: build_and_publish_docker_image

on:
  push:
    branches:
      - master
      - feat/add-docker-image
    paths:
      - 'chatsky/utils/docker/**'
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build_and_publish_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract Docker metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: docker.io/${{ github.repository }}
          flavor: |
            latest=auto
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Test Dockerfile
        run: docker build -t chatsky_image -f chatsky/utils/docker/chatsky/dockerfile_chatsky .    

      - name: Build and upload image
        uses: docker/build-push-action@v5
        with:
          context: chatsky
          file: chatsky/utils/docker/chatsky/dockerfile_chatsky
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
