name: test_coverage

on: [push]


jobs:
  linux_test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build images
        run: |
          docker-compose up -d

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: make venv
        shell: bash

      - name: build coverage file
        run: make test
        shell: bash

  macos_test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install docker-compose
        run: brew install docker docker-machine docker-compose

      - name: Build images
        run: |
          docker-compose up -d

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: make venv
        shell: bash

      - name: build coverage file
        run: make test
        shell: bash

  windows_test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[devel_full]
        shell: bash

      - name: build coverage file
        run: pytest --cache-clear --cov=dff tests/ > pytest-coverage.txt
        shell: bash