name: test_coverage

on:
  push:
    branches:
    - dev
    - test/**
  pull_request:
    branches:
    - dev
  workflow_dispatch:


jobs:
  test_coverage:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    env:
      HF_API_KEY: ${{ secrets.HF_API_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Create gdf_account.json
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: "gdf_account.json"
          json: ${{ secrets.GDF_ACCOUNT_JSON }}

      - name: Build images
        run: |
          docker-compose up -d

      - name: set up python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: install dependencies
        run: make venv_test
        shell: bash

      - name: build coverage file
        run: make test
        shell: bash
        env:
          - HF_API_KEY: ${{ secrets.HF_API_KEY }}
          - GDF_ACCOUNT_JSON: ${{ secrets.GDF_ACCOUNT_JSON }}