name: test_coverage

on:
  push:
    branches:
    - dev
    - test/**
  pull_request:
    branches:
    - dev


jobs:
  linux_test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    runs-on: ubuntu-latest

    env:
      HF_API_KEY: ${{ secrets.HF_API_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Create gdf_account.json
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: "gdf_account.json"
          json: ${{ secrets.GDF_ACCOUNT_JSON }}

      - name: Build images
        run: |
          docker-compose up -d

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: make venv_test
        shell: bash

      - name: build coverage file
        run: make test
        shell: bash

  non_linux_test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    env:
      HF_API_KEY: ${{ secrets.HF_API_KEY }}
      GDF_ACCOUNT_JSON: ./gdf_account.json

    steps:
      - uses: actions/checkout@v2

      - name: Create gdf_account.json
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: "gdf_account.json"
          json: ${{ secrets.GDF_ACCOUNT_JSON }}

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test_full]
        shell: bash

      - name: build coverage file
        run: pytest --tb=long -vv --cache-clear --cov=dff tests/
        shell: bash
