name: test_coverage

on:
  push:
    branches:
    - dev
    - test/**
  pull_request:
    branches:
    - dev
  workflow_dispatch:


jobs:
  test_coverage:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build images
        run: |
          docker-compose up -d

      - name: set up python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: install dependencies
        run: make venv_test
        shell: bash
      
      - name: create session file
        run: echo ${{ secrets.TG_SESSION }} | base64 --decode > anon.session
        shell: bash

      - name: build coverage file
        env:
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_API_ID: ${{ secrets.TG_API_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: make test
        shell: bash